name: restaurant_submit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.5.0
  google_fonts: ^6.3.1
  flutter_spinkit: ^5.2.2  
  lottie: ^3.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_local_notifications: ^15.0.0
  workmanager: ^0.9.0+3
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/loading.json
    - assets/animations/error.json
    - assets/animations/empty.json
  
